(()=>{
 const canvas=document.getElementById('view'),ctx=canvas.getContext('2d'),axisCanvas=document.getElementById('axisView'),actx=axisCanvas.getContext('2d'),el=id=>document.getElementById(id);
 const dirs=[{name:'X',v:[1,0,0],color:'#ed9a84'},{name:'X',v:[-1,0,0],color:'#ed9a84'},{name:'Y',v:[0,1,0],color:'#83c5bb'},{name:'Y',v:[0,-1,0],color:'#83c5bb'},{name:'Z',v:[0,0,1],color:'#c0e36b'},{name:'Z',v:[0,0,-1],color:'#c0e36b'}];
 let yaw=Math.PI/4,pitch=Math.atan(1/Math.sqrt(2)),scale=34,zoom=1,pan=[0,0],target=[0,0,0],points=[[0,0,0]],segments=[],previousDir=null,offsetPreviousDir=null,continuationDir=null,mouse=[0,0],hover=null,dragging=false,dragMode='rotate',lastDrag=[0,0],offsetStage=0,offsetDir=null,offsetSideDir=null,offsetAnchor=null,offsetRSteps=1,offsetHSteps=1,ghostDir=dirs[0],ghostEnd=[1,0,0],ghostSteps=1,dimensionMode=false,drawingPaused=true,dimensionInputs=[],cw=800,ch=500,dpr=1,activeProfile=null,profiles=[],pendingPipeChange=false,projectDirectoryHandle=null,rememberedProjectHandle=null,projectManifest=null,projectFileMode=false,currentIsometryId=null;
 const dot=(a,b)=>a.reduce((v,x,i)=>v+x*b[i],0),cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],add=(a,b)=>a.map((x,i)=>x+b[i]),mul=(a,k)=>a.map(x=>x*k),near=(a,b)=>a.every((x,i)=>Math.abs(x-b[i])<1e-6),mid=(a,b)=>a.map((x,i)=>(x+b[i])/2);
 function project(p){const q=p.map((x,i)=>x-target[i]),cy=Math.cos(yaw),sy=Math.sin(yaw),cp=Math.cos(pitch),sp=Math.sin(pitch),xx=(q[0]*cy-q[1]*sy)*scale*zoom,yy=-(q[0]*sp*sy+q[1]*sp*cy-q[2]*cp)*scale*zoom;return[cw/2+pan[0]+xx,ch*.56+pan[1]+yy]}
 function basis(v){const a=project([0,0,0]),b=project(v);return[b[0]-a[0],b[1]-a[1]]}
 function resizeTarget(){const xs=points.map(p=>p[0]),ys=points.map(p=>p[1]),zs=points.map(p=>p[2]);target=[(Math.min(...xs)+Math.max(...xs))/2,(Math.min(...ys)+Math.max(...ys))/2,(Math.min(...zs)+Math.max(...zs))/2];const oldScale=scale,oldZoom=zoom,oldPan=pan;scale=1;zoom=1;pan=[0,0];const xy=points.map(p=>project(p).map((v,i)=>v-(i===0?cw/2:ch*.56))),w=Math.max(1,...xy.map(p=>p[0]))-Math.min(-1,...xy.map(p=>p[0])),h=Math.max(1,...xy.map(p=>p[1]))-Math.min(-1,...xy.map(p=>p[1]));scale=oldScale;zoom=oldZoom;pan=oldPan;scale=Math.max(4,Math.min(70,(cw-180)/w,(ch-130)/h))}
 function resize(){const r=canvas.getBoundingClientRect();dpr=window.devicePixelRatio||1;cw=r.width;ch=r.height;canvas.width=Math.round(cw*dpr);canvas.height=Math.round(ch*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);const ar=axisCanvas.getBoundingClientRect();axisCanvas.width=Math.round(ar.width*dpr);axisCanvas.height=Math.round(ar.height*dpr);actx.setTransform(dpr,0,0,dpr,0,0);render()}
 function allowedDirs(){if(offsetStage===1&&offsetDir)return dirs.filter(d=>dot(d.v,offsetDir.v)===0);if(offsetStage===2&&offsetDir&&offsetSideDir){const out=dirs.filter(d=>dot(d.v,offsetSideDir.v)===0);if(offsetPreviousDir)for(const d of dirs)if(Math.abs(dot(d.v,offsetPreviousDir.v))===1&&!out.includes(d))out.push(d);return out}if(!offsetStage&&previousDir){const out=dirs.filter(d=>dot(d.v,previousDir.v)===0);if(continuationDir)for(const d of dirs)if(Math.abs(dot(d.v,continuationDir.v))===1&&!out.includes(d))out.push(d);return out}return dirs}
 function chooseDirection(dx,dy,choices=allowedDirs()){const mag=Math.hypot(dx,dy);if(!choices.length)return dirs[0];let best=choices[0],score=-Infinity;for(const d of choices){const [vx,vy]=basis(d.v),m=Math.hypot(vx,vy)||1,s=mag<2?0:(dx*vx+dy*vy)/(mag*m);if(s>score){score=s;best=d}}return best}
 function previewOrigin(){if(offsetStage===1)return add(offsetAnchor,mul(offsetDir.v,offsetRSteps));if(offsetStage===2)return add(add(offsetAnchor,mul(offsetDir.v,offsetRSteps)),mul(offsetSideDir.v,offsetHSteps));return points.at(-1)}
 function moveEnd(pos,thirdAxisOnly=false){mouse=pos;const o=project(previewOrigin()),dx=pos[0]-o[0],dy=pos[1]-o[1],choices=thirdAxisOnly&&offsetStage===2?dirs.filter(d=>dot(d.v,offsetDir.v)===0&&dot(d.v,offsetSideDir.v)===0):allowedDirs();ghostDir=chooseDirection(dx,dy,choices);const [vx,vy]=basis(ghostDir.v),vl=Math.hypot(vx,vy)||1;ghostSteps=Math.max(1,Math.min(30,Math.round((dx*vx+dy*vy)/(vl*vl))));ghostEnd=add(previewOrigin(),mul(ghostDir.v,ghostSteps));hover=pos;el('coordText').textContent=ghostEnd.map(v=>Math.round(v*10)/10).join(' · ');render()}
 function gridRange(){return Math.min(22,Math.max(7,...points.flatMap(p=>p.map(Math.abs)))+3)}
 function line(a,b,color,width=1,dash=[]){const p=project(a),q=project(b);ctx.beginPath();ctx.moveTo(...p);ctx.lineTo(...q);ctx.strokeStyle=color;ctx.lineWidth=width;ctx.setLineDash(dash);ctx.stroke();ctx.setLineDash([])}
 function renderGrid(){const n=gridRange(),c=target.map(Math.round),seen=new Set();ctx.save();for(let plane=0;plane<3;plane++)for(let a=-n;a<=n;a++)for(let b=-n;b<=n;b++){const p=plane===0?[c[0]+a,c[1]+b,c[2]]:plane===1?[c[0]+a,c[1],c[2]+b]:[c[0],c[1]+a,c[2]+b],[x,y]=project(p),key=`${Math.round(x)}:${Math.round(y)}`;if(seen.has(key)||x<0||x>cw||y<0||y>ch)continue;seen.add(key);ctx.fillStyle='rgba(164,187,174,.62)';ctx.beginPath();ctx.arc(x,y,1.5,0,Math.PI*2);ctx.fill()}ctx.restore()}
 function renderAxes(){for(const d of dirs.filter(x=>x.v.some(v=>v>0))){line([0,0,0],mul(d.v,4),'#607268',1);const p=project(mul(d.v,4.5));ctx.fillStyle=d.color;ctx.font='11px Segoe UI';ctx.fillText(d.name,p[0],p[1])}}
 function renderAxisWidget(){const r=axisCanvas.getBoundingClientRect(),w=r.width,h=r.height;actx.clearRect(0,0,w,h);actx.fillStyle='#18221ed9';actx.strokeStyle='#3b4a41';actx.beginPath();actx.roundRect(1,1,w-2,h-2,7);actx.fill();actx.stroke();const c=[w*.5,h*.51],len=Math.min(w,h)*.27;for(const d of dirs.filter(x=>x.v.some(v=>v>0))){const [bx,by]=basis(d.v),m=Math.hypot(bx,by)||1,x=c[0]+bx/m*len,y=c[1]+by/m*len;actx.beginPath();actx.moveTo(...c);actx.lineTo(x,y);actx.strokeStyle=d.color;actx.lineWidth=2;actx.stroke();actx.fillStyle=d.color;actx.beginPath();actx.arc(x,y,3,0,Math.PI*2);actx.fill();actx.font='9px Segoe UI';actx.fillText(d.name,x+4,y-3)}}
 function label(p,t,color){const [x,y]=project(p);ctx.font='700 13px Segoe UI';ctx.textAlign='center';ctx.textBaseline='middle';ctx.lineWidth=4;ctx.strokeStyle='#111816';ctx.strokeText(t,x,y);ctx.fillStyle=color;ctx.fillText(t,x,y);ctx.textAlign='start';ctx.textBaseline='alphabetic'}
 function drawOffset(s){const R=s.drawR,H=s.drawH,V=s.drawV,rp=add(s.anchor,mul(s.runDir.v,R)),sp=add(rp,mul(s.sideDir.v,H)),end=add(sp,mul(s.vertDir.v,V));s.runPoint=rp;s.sidePoint=sp;s.to=end;line(s.anchor,rp,'#f06b27',3);line(rp,end,'#e52c2b',3);line(rp,sp,'#168dce',2,[5,4]);if(V)line(sp,end,'#23a45a',2,[5,4]);line(s.anchor,end,'#eb4f9a',5);label(mid(s.anchor,rp),s.R?`R ${s.R} mm`:'R','#ff762e');label(mid(rp,sp),s.H?`H ${s.H} mm`:'H','#41b7fa');if(V)label(mid(sp,end),s.V?`V ${s.V} mm`:'V','#51dc82');if(s.R&&s.H&&(V===0||s.V)){const dh=s.H,dv=s.V||0,C=Math.hypot(dh,dv),angle=Math.atan2(C,s.R)*180/Math.PI,T=Math.hypot(s.R,C);label(mid(rp,end),`C ${C.toFixed(1)} mm`,'#ff4540');label(mid(s.anchor,end),`T ${T.toFixed(1)} mm`,'#ff86c1');label(end,`${angle.toFixed(1)}°`,'#ff86c1')}const lo=s.anchor.map((v,i)=>Math.min(v,end[i])),hi=s.anchor.map((v,i)=>Math.max(v,end[i]));for(let mask=0;mask<8;mask++)for(let axis=0;axis<3;axis++)if(!(mask&(1<<axis))){const a=lo.map((v,i)=>mask&(1<<i)?hi[i]:v),b=[...a];b[axis]=hi[axis];if(a.some((v,i)=>Math.abs(v-b[i])>1e-8))line(a,b,'#72859b',1,[3,5])}}
 function render(){if(!ctx||!cw)return;ctx.clearRect(0,0,cw,ch);const bg=ctx.createLinearGradient(0,0,0,ch);bg.addColorStop(0,'#17201d');bg.addColorStop(1,'#111816');ctx.fillStyle=bg;ctx.fillRect(0,0,cw,ch);renderGrid();renderAxes();for(const s of segments){if(s.kind==='offset'){drawOffset(s);continue}line(s.from,s.to,'#c0e36b',5);if(s.length)label(mid(s.from,s.to),`${s.length} mm`,'#e1f5b2');const p=project(s.to);ctx.beginPath();ctx.arc(...p,4,0,Math.PI*2);ctx.fillStyle='#d9f59a';ctx.fill()}if(hover&&!dimensionMode&&!drawingPaused){if(offsetStage===1)line(offsetAnchor,previewOrigin(),'#c0e36b',4);if(offsetStage===2){const rp=add(offsetAnchor,mul(offsetDir.v,offsetRSteps));line(offsetAnchor,rp,'#c0e36b',4);line(rp,previewOrigin(),'#c0e36b',4)}line(previewOrigin(),ghostEnd,offsetStage?'#83c5bb':'#dff5a9',3,[7,5]);const e=project(ghostEnd);ctx.beginPath();ctx.arc(e[0],e[1],5,0,Math.PI*2);ctx.fillStyle='#e5f8b9';ctx.fill()}const p0=project(points[0]);ctx.beginPath();ctx.arc(p0[0],p0[1],5,0,Math.PI*2);ctx.fillStyle='#f0f4ef';ctx.fill();renderAxisWidget();if(dimensionMode)positionDimensionInputs()}
 function recalc(){let p=[0,0,0];points=[p];for(const s of segments){if(s.kind==='pipe'){s.from=[...p];s.to=add(p,mul(s.dir,s.drawLength));p=[...s.to]}else{s.anchor=[...p];s.runPoint=add(p,mul(s.runDir.v,s.drawR));s.sidePoint=add(s.runPoint,mul(s.sideDir.v,s.drawH));s.to=add(s.sidePoint,mul(s.vertDir.v,s.drawV));s.from=[...p];p=[...s.to]}points.push([...p])}resizeTarget();updateSawLength();updateBendPositions();updateProjectControls()}
 function finishOffset(threeD){const s={kind:'offset',runDir:offsetDir,sideDir:offsetSideDir,vertDir:threeD?ghostDir:{v:[0,0,0]},drawR:offsetRSteps,drawH:offsetHSteps,drawV:threeD?ghostSteps:0,R:null,H:null,V:threeD?null:0};segments.push(s);continuationDir=threeD?null:offsetPreviousDir;previousDir=threeD?ghostDir:offsetSideDir;offsetStage=0;offsetDir=offsetSideDir=offsetAnchor=offsetPreviousDir=null;recalc();updatePrompt();render()}
 function commit(kind){if(dimensionMode||drawingPaused||!activeProfile)return;if(!hover){const r=canvas.getBoundingClientRect();moveEnd([r.width*.64,r.height*.5])}if(kind==='pipe'){if(offsetStage===2)finishOffset(false);else if(offsetStage===1){offsetStage=0;offsetDir=offsetAnchor=offsetPreviousDir=null}if(hover)moveEnd(hover);if(near(points.at(-1),ghostEnd))return;segments.push({kind:'pipe',dir:[...ghostDir.v],drawLength:ghostSteps,length:null});previousDir=ghostDir;continuationDir=null;recalc();updatePrompt();if(hover)moveEnd(hover);return}if(offsetStage===0){offsetAnchor=[...points.at(-1)];offsetPreviousDir=previousDir;offsetDir=ghostDir;offsetRSteps=ghostSteps;offsetStage=1;updatePrompt();render();return}if(offsetStage===1){offsetSideDir=ghostDir;offsetHSteps=ghostSteps;offsetStage=2;updatePrompt();render();return}finishOffset(true);if(hover)moveEnd(hover)}
 function dimensionItems(){const out=[];segments.forEach((s,i)=>{if(s.kind==='pipe')out.push({s,key:'length',label:`L${i+1}`,a:s.from,b:s.to});else{out.push({s,key:'R',label:'R',a:s.anchor,b:s.runPoint},{s,key:'H',label:'H',a:s.runPoint,b:s.sidePoint});if(s.drawV)out.push({s,key:'V',label:'V',a:s.sidePoint,b:s.to})}});return out}
 function positionDimensionInputs(){if(!dimensionMode)return;dimensionItems().forEach((item,i)=>{const p=project(mid(item.a,item.b));dimensionInputs[i].style.left=`${p[0]}px`;dimensionInputs[i].style.top=`${p[1]}px`})}
 function startDimensioning(){if(!activeProfile){showProfileDialog();return}if(offsetStage===2)finishOffset(false);else if(offsetStage===1){offsetStage=0;offsetDir=offsetAnchor=null}drawingPaused=false;dimensionMode=true;hover=null;el('toolMode').textContent='BEMAẞEN';el('dimension').textContent='Zeichnen';el('prompt').innerHTML='<b>Maße eingeben</b> · Feld an der Strecke ausfüllen und Enter drücken.';const box=el('dimensionFields');box.replaceChildren();dimensionInputs=dimensionItems().map((item,i)=>{const input=document.createElement('input');input.className='dim-field';input.type='number';input.min='0';input.step='any';input.placeholder=`${item.label} · mm`;input.value=item.s[item.key]??'';input.setAttribute('aria-label',`${item.label} in Millimeter`);input.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();const value=Number(input.value);if(!(value>0)){input.focus();return}item.s[item.key]=value;recalc();render();if(i<dimensionInputs.length-1)dimensionInputs[i+1].focus();else stopDimensioning(true)}});box.append(input);return input});positionDimensionInputs();if(dimensionInputs.length)dimensionInputs[0].focus()}
 function stopDimensioning(pauseDrawing=true){dimensionMode=false;drawingPaused=pauseDrawing;hover=null;el('toolMode').textContent=pauseDrawing?'BEREIT':'ZEICHNEN · 3D';el('dimension').textContent=pauseDrawing?'Weiterzeichnen':'Bemaßen';el('dimensionFields').replaceChildren();dimensionInputs=[];updatePrompt();updateSawLength();updateBendPositions();render()}
 function resumeDrawing(){if(!activeProfile){showProfileDialog();return}drawingPaused=false;hover=null;el('toolMode').textContent='ZEICHNEN · 3D';el('dimension').textContent='Bemaßen';updatePrompt();render()}
 const profileStorageKey='rohrplan.pipe-profiles.v1';
 function loadProfiles(){try{const saved=localStorage.getItem(profileStorageKey);profiles=saved?JSON.parse(saved):[];if(!Array.isArray(profiles))profiles=[]}catch{profiles=[]}}
 function persistProfiles(next){try{localStorage.setItem(profileStorageKey,JSON.stringify(next));profiles=next;return true}catch{alert('Der Datensatz konnte im Browser nicht gespeichert werden.');return false}}
 function profileName(p){return `Ø ${p.diameter} × ${p.wall} mm · R ${p.radius} mm`}
 function refreshProfileOptions(){const select=el('profileSelect'),old=select.value;select.replaceChildren(new Option('Bitte Datensatz wählen',''));[...profiles].sort((a,b)=>a.diameter-b.diameter||a.wall-b.wall||a.radius-b.radius).forEach(p=>select.add(new Option(profileName(p),p.id)));if(profiles.some(p=>p.id===old))select.value=old;el('profileEmpty').hidden=profiles.length>0;el('startPipe').disabled=!select.value}
 function renderProfileList(){const list=el('profileList');list.replaceChildren();if(!profiles.length){const empty=document.createElement('div');empty.className='dialog-note';empty.textContent='Noch keine Datensätze gespeichert.';list.append(empty);return}profiles.forEach(p=>{const row=document.createElement('div');row.className='profile-row';const info=document.createElement('div'),title=document.createElement('strong'),detail=document.createElement('small'),remove=document.createElement('button');title.textContent=profileName(p);const cal=calibration(p);detail.textContent=`Muster: ${p.sampleLength} mm gerade · Außenmaße ${p.legs.join(' / ')} mm · Korrektur ${cal.per90>=0?'+':''}${cal.per90.toFixed(2)} mm je 90°`;info.append(title,detail);remove.type='button';remove.className='button delete-profile';remove.textContent='Löschen';remove.setAttribute('aria-label',`${profileName(p)} löschen`);remove.dataset.profileId=p.id;row.append(info,remove);list.append(row)})}
 function deleteProfile(id){const profile=profiles.find(p=>p.id===id);if(!profile||!confirm(`Rohrdatensatz „${profileName(profile)}“ wirklich löschen?`))return;if(!persistProfiles(profiles.filter(p=>p.id!==id)))return;refreshProfileOptions();renderProfileList()}
 const projectManifestFile='rohrplan-project.json';
 function makeDesktopDirectoryHandle(info){const api=window.rohrPlanDesktop;return{kind:'directory',name:info.name,path:info.path,getDirectoryHandle:async(name,options={})=>makeDesktopDirectoryHandle(await api.ensureDirectory(info.path,name,!!options.create)),getFileHandle:async(name)=>({kind:'file',name,getFile:async()=>new File([await api.readFile(info.path,name)],name,{type:'application/json'}),createWritable:async()=>{let contents='';return{write:async value=>{contents=typeof value==='string'?value:JSON.stringify(value)},close:async()=>api.writeFile(info.path,name,contents)}}}),removeEntry:name=>api.removeFile(info.path,name),queryPermission:async()=> 'granted',requestPermission:async()=> 'granted'} }
 if(window.rohrPlanDesktop)window.showDirectoryPicker=async()=>{const selected=await window.rohrPlanDesktop.pickDirectory();if(!selected){const error=new Error('Ordnerauswahl abgebrochen.');error.name='AbortError';throw error}return makeDesktopDirectoryHandle(selected)};
 const projectHandleDb='rohrplan-browser-storage',projectHandleStore='directory-handles';
 function openProjectHandleDb(){return new Promise((resolve,reject)=>{if(!('indexedDB'in window)){reject(new Error('IndexedDB nicht verfügbar'));return}const request=indexedDB.open(projectHandleDb,1);request.onupgradeneeded=()=>request.result.createObjectStore(projectHandleStore);request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
 async function saveRememberedProjectHandle(handle){const db=await openProjectHandleDb();try{await new Promise((resolve,reject)=>{const tx=db.transaction(projectHandleStore,'readwrite');tx.objectStore(projectHandleStore).put(window.rohrPlanDesktop?{desktopPath:handle.path,name:handle.name}:handle,'active');tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error)})}finally{db.close()}}
 async function readRememberedProjectHandle(){const db=await openProjectHandleDb();try{const stored=await new Promise((resolve,reject)=>{const tx=db.transaction(projectHandleStore,'readonly'),request=tx.objectStore(projectHandleStore).get('active');request.onsuccess=()=>resolve(request.result||null);request.onerror=()=>reject(request.error)});return window.rohrPlanDesktop&&stored?.desktopPath?makeDesktopDirectoryHandle({path:stored.desktopPath,name:stored.name}):stored}finally{db.close()}}
 function updateProjectControls(){const hasDrawing=!!activeProfile&&segments.length>0;el('saveIsometry').disabled=!hasDrawing;el('saveCurrentToProject').disabled=!(projectDirectoryHandle||projectFileMode)||!hasDrawing;el('projectCurrentStatus').textContent=projectDirectoryHandle?`Geöffnetes Projekt: ${projectManifest?.projectName||projectDirectoryHandle.name} · Ordner: ${projectDirectoryHandle.path||projectDirectoryHandle.name}`:projectFileMode?`Projektdatei „${projectManifest?.projectName||'Projekt'}“ geöffnet · Änderungen werden als lokale JSON-Datei heruntergeladen.`:rememberedProjectHandle?`Zuletzt verwendet: „${rememberedProjectHandle.name}“ · Zugriff über „Projekt“ wiederherstellen.`:!window.rohrPlanDesktop&&!window.showDirectoryPicker?'Ordnerzugriff ist hier gesperrt. Du kannst stattdessen ein Projekt als JSON-Datei auf dem Rechner anlegen oder öffnen.':'Kein Projektordner geöffnet.'}
 function safeFolderName(name){return name.trim().replace(/[<>:"/\\|?*\u0000-\u001f]/g,'_').replace(/[. ]+$/,'')}
 async function writeProjectManifest(){const file=await projectDirectoryHandle.getFileHandle(projectManifestFile,{create:true}),writer=await file.createWritable();await writer.write(JSON.stringify(projectManifest,null,2));await writer.close()}
 function isMissingProjectFile(error){return error?.name==='NotFoundError'||/\bENOENT\b|no such file/i.test(error?.message||'')}
 async function activateProject(handle,initializeIfMissing=false){let manifest;try{const file=await handle.getFileHandle(projectManifestFile),data=await file.getFile();manifest=JSON.parse(await data.text());if(manifest.formatVersion!==1||!Array.isArray(manifest.isometries))throw new Error('Die Projektdatei hat ein nicht unterstütztes Format.')}catch(error){if(!isMissingProjectFile(error))throw error;if(!initializeIfMissing&&!confirm(`In „${handle.name}“ wurde noch kein RohrPlan-Projekt gefunden. Diesen Ordner als Projekt einrichten?`))return false;manifest={formatVersion:1,projectName:handle.name,isometries:[]};projectDirectoryHandle=handle;projectManifest=manifest;await writeProjectManifest()}projectDirectoryHandle=handle;rememberedProjectHandle=handle;projectManifest=manifest;currentIsometryId=null;saveRememberedProjectHandle(handle).catch(()=>{});renderProjectIsometries();updateProjectControls();return true}
 async function restoreRememberedProject(){try{rememberedProjectHandle=await readRememberedProjectHandle();if(!rememberedProjectHandle){updateProjectControls();return}const permission=await rememberedProjectHandle.queryPermission({mode:'readwrite'});if(permission==='granted'){await activateProject(rememberedProjectHandle,false)}else updateProjectControls()}catch{rememberedProjectHandle=null;updateProjectControls()}}
 function openProjectsDialog(){if(rememberedProjectHandle&&!projectDirectoryHandle&&typeof rememberedProjectHandle.requestPermission==='function'){const permissionRequest=rememberedProjectHandle.requestPermission({mode:'readwrite'});permissionRequest.then(async permission=>{if(permission==='granted'){try{await activateProject(rememberedProjectHandle,false)}catch(error){el('projectCurrentStatus').textContent=`Projektzugriff fehlgeschlagen: ${error.message}`}}else updateProjectControls()}).catch(()=>{});}renderProjectIsometries();updateProjectControls();el('projectDialog').showModal()}
 function downloadProjectFile(){const blob=new Blob([JSON.stringify(projectManifest,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`RohrPlan-${safeFolderName(projectManifest.projectName)||'Projekt'}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 function loadDownloadedProject(file){const reader=new FileReader();reader.onload=()=>{try{const manifest=JSON.parse(reader.result);if(manifest.formatVersion!==1||!Array.isArray(manifest.isometries)||manifest.isometries.some(item=>!item.data))throw new Error('Die Datei ist kein vollständiges RohrPlan-Projekt.');projectDirectoryHandle=null;rememberedProjectHandle=null;projectFileMode=true;projectManifest=manifest;currentIsometryId=null;el('newProjectName').value=manifest.projectName||'';el('currentIsometryName').value=`Isometrie ${manifest.isometries.length+1}`;renderProjectIsometries();updateProjectControls()}catch(error){el('projectCurrentStatus').textContent=`Projektdatei konnte nicht geöffnet werden: ${error.message}`}};reader.onerror=()=>{el('projectCurrentStatus').textContent='Die ausgewählte Projektdatei konnte nicht gelesen werden.'};reader.readAsText(file)}
 async function createProjectFolder(){const name=safeFolderName(el('newProjectName').value);if(!name){el('projectCurrentStatus').textContent='Bitte zuerst einen gültigen Projektnamen eingeben.';return}if(!window.showDirectoryPicker){projectDirectoryHandle=null;rememberedProjectHandle=null;projectFileMode=true;projectManifest={formatVersion:1,projectName:name,isometries:[]};currentIsometryId=null;renderProjectIsometries();downloadProjectFile();updateProjectControls();el('projectCurrentStatus').textContent='Projektdatei wurde in deinen Downloads gespeichert. Nach jeder Änderung wird eine aktualisierte JSON-Datei heruntergeladen.';return}try{const parent=await window.showDirectoryPicker({mode:'readwrite'}),handle=await parent.getDirectoryHandle(name,{create:true});const opened=await activateProject(handle,true);if(opened){el('newProjectName').value=name;el('currentIsometryName').value=`Isometrie ${projectManifest.isometries.length+1}`;el('projectCurrentStatus').textContent=`Projekt „${name}“ ist geöffnet.`}}catch(error){if(error.name!=='AbortError')el('projectCurrentStatus').textContent=`Projektordner konnte nicht erstellt werden: ${error.message}`}}
 async function openProjectFolder(){if(!window.showDirectoryPicker){el('projectFileInput').value='';el('projectFileInput').click();return}try{const handle=await window.showDirectoryPicker({mode:'readwrite'});if(await activateProject(handle,false)){el('newProjectName').value=projectManifest.projectName;el('currentIsometryName').value=`Isometrie ${projectManifest.isometries.length+1}`}}catch(error){if(error.name!=='AbortError')el('projectCurrentStatus').textContent=`Projektordner konnte nicht geöffnet werden: ${error.message}`}}
 function renderProjectIsometries(){const list=el('projectIsometryList');list.replaceChildren();if(!projectManifest?.isometries?.length){const empty=document.createElement('p');empty.className='project-empty';empty.textContent=projectDirectoryHandle?'In diesem Projekt sind noch keine Isometrien gespeichert.':'Öffne oder erstelle zuerst ein Projekt.';list.append(empty);return}for(const item of [...projectManifest.isometries].sort((a,b)=>b.savedAt.localeCompare(a.savedAt))){const row=document.createElement('div');row.className='project-isometry-row';const info=document.createElement('div'),name=document.createElement('strong'),meta=document.createElement('small');name.textContent=item.name;meta.textContent=`Gespeichert ${new Date(item.savedAt).toLocaleString('de-DE')}`;info.append(name,meta);const actions=document.createElement('div'),load=document.createElement('button'),remove=document.createElement('button');load.type=remove.type='button';load.className='button primary';load.textContent='Laden';load.onclick=()=>loadProjectIsometry(item.id);remove.className='button clear';remove.textContent='Löschen';remove.onclick=()=>deleteProjectIsometry(item.id);actions.className='project-isometry-actions';actions.append(load,remove);row.append(info,actions);list.append(row)}}
 function serializeIsometry(name,id){return{formatVersion:1,id,name,savedAt:new Date().toISOString(),profile:JSON.parse(JSON.stringify(activeProfile)),view:{yaw,pitch,zoom,pan:[...pan]},segments:segments.map(s=>s.kind==='pipe'?{kind:'pipe',dir:[...s.dir],drawLength:s.drawLength,length:s.length}:{kind:'offset',runDir:[...s.runDir.v],sideDir:[...s.sideDir.v],vertDir:[...s.vertDir.v],drawR:s.drawR,drawH:s.drawH,drawV:s.drawV,R:s.R,H:s.H,V:s.V})}}
 async function saveCurrentIsometry(){if(!projectDirectoryHandle&&!projectFileMode){el('projectCurrentStatus').textContent='Lege zuerst ein Projekt an oder öffne eine Projektdatei.';if(!el('projectDialog').open)el('projectDialog').showModal();return}if(!activeProfile||!segments.length)return;const name=el('currentIsometryName').value.trim()||'Isometrie';let item=projectManifest.isometries.find(x=>x.id===currentIsometryId);if(!item){currentIsometryId=globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`;item={id:currentIsometryId,fileName:`isometrie-${currentIsometryId}.json`};projectManifest.isometries.unshift(item)}item.name=name;item.savedAt=new Date().toISOString();const data=serializeIsometry(name,item.id);try{if(projectFileMode){item.data=data;downloadProjectFile()}else{const file=await projectDirectoryHandle.getFileHandle(item.fileName,{create:true}),writer=await file.createWritable();await writer.write(JSON.stringify(data,null,2));await writer.close();await writeProjectManifest()}el('currentIsometryName').value=name;renderProjectIsometries();updateProjectControls();el('projectCurrentStatus').textContent=projectFileMode?`„${name}“ wurde gespeichert. Die aktualisierte Projektdatei liegt in Downloads; ersetze dort die ältere Datei.`:`„${name}“ wurde in „${projectDirectoryHandle.name}“ gespeichert.`}catch(error){el('projectCurrentStatus').textContent=`Isometrie konnte nicht gespeichert werden: ${error.message}`}}
 function directionFromVector(vector){return dirs.find(d=>near(d.v,vector))||{name:'',v:[...vector],color:'#83c5bb'}}
 async function loadProjectIsometry(id){const item=projectManifest?.isometries.find(x=>x.id===id);if(!item)return;if(segments.length&&!confirm('Die aktuelle Zeichnung wird durch die gespeicherte Isometrie ersetzt. Fortfahren?'))return;try{const payload=item.data||JSON.parse(await(await(await projectDirectoryHandle.getFileHandle(item.fileName)).getFile()).text());if(payload.formatVersion!==1||!Array.isArray(payload.segments)||!payload.profile)throw new Error('Die Isometrie-Datei ist ungültig oder wird nicht unterstützt.');segments=payload.segments.map(s=>s.kind==='pipe'?{...s,dir:[...s.dir]}:{...s,runDir:directionFromVector(s.runDir),sideDir:directionFromVector(s.sideDir),vertDir:directionFromVector(s.vertDir)});activeProfile=payload.profile;currentIsometryId=item.id;el('currentIsometryName').value=item.name;el('activeProfileLabel').textContent=profileName(activeProfile);if(payload.view){yaw=Number(payload.view.yaw)||yaw;pitch=Number(payload.view.pitch)||pitch;zoom=Number(payload.view.zoom)||1;pan=Array.isArray(payload.view.pan)?payload.view.pan:[0,0]}dimensionMode=false;dimensionInputs=[];el('dimensionFields').replaceChildren();el('dimension').textContent='Bemaßen';drawingPaused=false;offsetStage=0;offsetDir=offsetSideDir=offsetAnchor=offsetPreviousDir=null;const last=segments.at(-1);previousDir=last?directionFromVector(last.kind==='pipe'?last.dir:(last.drawV?last.vertDir.v:last.sideDir.v)):null;continuationDir=null;recalc();updatePrompt();resize();render();updateProjectControls();el('projectDialog').close()}catch(error){alert(`Isometrie konnte nicht geladen werden: ${error.message}`)}}
 async function deleteProjectIsometry(id){const item=projectManifest?.isometries.find(x=>x.id===id);if(!item||!confirm(`„${item.name}“ aus diesem Projekt löschen?`))return;try{if(projectFileMode){projectManifest.isometries=projectManifest.isometries.filter(x=>x.id!==id);downloadProjectFile()}else{await projectDirectoryHandle.removeEntry(item.fileName);projectManifest.isometries=projectManifest.isometries.filter(x=>x.id!==id);await writeProjectManifest()}if(currentIsometryId===id)currentIsometryId=null;renderProjectIsometries();updateProjectControls()}catch(error){alert(`Isometrie konnte nicht gelöscht werden: ${error.message}`)}}
 function calibration(p){const outsideTotal=p.legs.reduce((a,b)=>a+b,0),theoretical=outsideTotal-2*p.diameter-(4-Math.PI)*p.radius;return{theoretical,per90:(p.sampleLength-theoretical)/2}}
 function updateCalibrationPreview(){const p={diameter:Number(el('recordDiameter').value),radius:Number(el('recordRadius').value),sampleLength:Number(el('recordStartLength').value),legs:[1,2,3].map(i=>Number(el(`recordLeg${i}`).value))},out=el('calibrationPreview');if(![p.diameter,p.radius,p.sampleLength,...p.legs].every(x=>x>0)){out.textContent='Die Messwerte werden zur Kalibrierung für diesen Rohrdatensatz gespeichert.';return}const c=calibration(p);out.textContent=`Theoretische Mittellinien-Sägelänge des Musters: ${c.theoretical.toFixed(1)} mm. Daraus ermittelte Korrektur: ${c.per90>=0?'+':''}${c.per90.toFixed(2)} mm je 90°-Biegung.`}
 function sawLength(){if(!activeProfile||!segments.length)return null;const legs=[];for(const s of segments){if(s.kind==='pipe'){if(!(s.length>0))return null;legs.push({dir:s.dir,len:s.length})}else{if(!(s.R>0&&s.H>0))return null;const v=add(add(mul(s.runDir.v,s.R),mul(s.sideDir.v,s.H)),s.V>0?mul(s.vertDir.v,s.V):[0,0,0]),len=Math.hypot(...v);if(!(len>0))return null;legs.push({dir:v.map(x=>x/len),len,offset:true})}}const cal=calibration(activeProfile),radius=activeProfile.radius;let total=legs.reduce((sum,l)=>sum+l.len,0),bends=0;for(let i=1;i<legs.length;i++){const d=Math.max(-1,Math.min(1,dot(legs[i-1].dir,legs[i].dir)));if(d<-.999999)return{error:'Eine 180°-Umlenkung ist mit dem U-Muster nicht kalibriert.'};const angle=Math.acos(d);if(angle<1e-6)continue;const tangentSetback=radius*Math.tan(angle/2),arc=radius*angle,empirical=cal.per90*angle/(Math.PI/2);/* Each drawn leg reaches the theoretical sharp corner, so remove the tangent setback from both legs meeting at this bend. */total+=arc-2*tangentSetback+empirical;bends++}return{length:total,bends}}
 function sawLength(){if(!activeProfile||!segments.length)return null;const legs=[];for(const s of segments){if(s.kind==='pipe'){if(!(s.length>0))return null;legs.push({dir:s.dir,len:s.length})}else{if(!(s.R>0&&s.H>0))return null;const v=add(add(mul(s.runDir.v,s.R),mul(s.sideDir.v,s.H)),s.V>0?mul(s.vertDir.v,s.V):[0,0,0]),len=Math.hypot(...v);if(!(len>0))return null;legs.push({dir:v.map(x=>x/len),len,offset:true})}}const cal=calibration(activeProfile),radius=activeProfile.radius;let total=legs.reduce((sum,l)=>sum+l.len,0),bends=0;for(let i=1;i<legs.length;i++){const d=Math.max(-1,Math.min(1,dot(legs[i-1].dir,legs[i].dir)));if(d<-.999999)return{error:'Eine 180°-Umlenkung ist mit dem U-Muster nicht kalibriert.'};const angle=Math.acos(d);if(angle<1e-6)continue;const tangentSetback=radius*Math.tan(angle/2),arc=radius*angle,empirical=cal.per90*angle/(Math.PI/2);/* Each drawn leg reaches the theoretical sharp corner, so remove the tangent setback from both legs meeting at this bend. */total+=arc-2*tangentSetback+empirical;bends++}return{length:total,bends}}
 function chuckExtension(){if(!segments.length)return null;const last=segments.at(-1);let tail;if(last.kind==='pipe')tail=last.length;else{if(last.drawV>0&&!(last.V>0))return null;tail=last.drawV>0?last.V:last.H}return tail>0?Math.max(0,305-tail):null}
 function sawLengthWithChuck(){const result=sawLength();if(!result||result.error)return result;const extension=chuckExtension();if(extension===null)return null;return{...result,length:result.length+extension,chuckExtension:extension}}
 function bendPositions(){if(!activeProfile||!segments.length)return null;const legs=[];for(const s of segments){if(s.kind==='pipe'){if(!(s.length>0))return null;legs.push({dir:s.dir,len:s.length})}else{if(!(s.R>0&&s.H>0)||s.drawV>0&&!(s.V>0))return null;const v=add(add(mul(s.runDir.v,s.R),mul(s.sideDir.v,s.H)),s.V>0?mul(s.vertDir.v,s.V):[0,0,0]),len=Math.hypot(...v);if(!(len>0))return null;legs.push({dir:v.map(x=>x/len),len})}}const radius=activeProfile.radius,out=[];let virtualDistance=0,previousBendAdjustment=0;for(let i=1;i<legs.length;i++){virtualDistance+=legs[i-1].len;const d=Math.max(-1,Math.min(1,dot(legs[i-1].dir,legs[i].dir)));if(d<-.999999)return{error:'180°-Biegungen sind noch nicht abgebildet.'};const angle=Math.acos(d);if(angle<1e-6)continue;const tangentSetback=radius*Math.tan(angle/2),position=virtualDistance+previousBendAdjustment-tangentSetback;if(position<0)return{error:'Die erste Biegeposition liegt vor dem Rohranfang.'};const normal=mul(cross(legs[i-1].dir,legs[i].dir),1/Math.sin(angle));let rotation=0;if(out.length){const previous=out.at(-1),axis=legs[i-1].dir,step=Math.atan2(dot(axis,cross(previous.plane,normal)),dot(previous.plane,normal))*180/Math.PI;rotation=(previous.rotation+step+360)%360;if(Math.abs(rotation-360)<1e-7||Math.abs(rotation)<1e-7)rotation=0}out.push({number:out.length+1,segmentIndex:i,angle,position,rotation,plane:normal});previousBendAdjustment+=radius*angle-2*tangentSetback}const cut=sawLengthWithChuck();if(!cut)return null;if(cut.error)return cut;return out.map(b=>({...b,position:cut.length-b.position}))}
 function drawBendSketch(bends){
  const svg=el('bendSketch');svg.replaceChildren();
  const ns='http://www.w3.org/2000/svg',make=(tag,attrs={},value)=>{const node=document.createElementNS(ns,tag);for(const [key,val]of Object.entries(attrs))node.setAttribute(key,val);if(value!=null)node.textContent=value;return node};
  const route=segments.length?[segments[0].from||[0,0,0],...segments.map(s=>s.to)]:[];
  if(!route.length){svg.append(make('text',{x:700,y:280,'text-anchor':'middle',class:'sketch-empty'},'Noch kein Rohrverlauf'));return}
  const projected=route.map(p=>project(p)),xs=projected.map(p=>p[0]),ys=projected.map(p=>p[1]),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys),width=1400,height=560,pad=65,scale=Math.min((width-2*pad)/Math.max(maxX-minX,1),(height-2*pad)/Math.max(maxY-minY,1)),points=projected.map(p=>({x:pad+(p[0]-minX)*scale,y:pad+(maxY-p[1])*scale}));
  svg.append(make('path',{d:points.map((p,i)=>`${i?'L':'M'} ${p.x} ${p.y}`).join(' '),class:'sketch-pipe'}));
  const start=points[0],end=points.at(-1);svg.append(make('circle',{cx:start.x,cy:start.y,r:7,class:'sketch-end'}),make('text',{x:start.x,y:start.y+34,'text-anchor':'middle',class:'sketch-end-label'},'Rohranfang'),make('circle',{cx:end.x,cy:end.y,r:7,class:'sketch-end'}),make('text',{x:end.x,y:end.y+34,'text-anchor':'middle',class:'sketch-end-label'},'Rohrende'));
  if(Array.isArray(bends))bends.forEach(b=>{const p=points[b.segmentIndex];if(!p)return;const positions=[{dx:12,dy:-14},{dx:-30,dy:-14},{dx:12,dy:30},{dx:-30,dy:30}],{dx,dy}=positions[(b.number-1)%positions.length];svg.append(make('circle',{cx:p.x,cy:p.y,r:6,class:'sketch-bend'}),make('text',{x:p.x+dx,y:p.y+dy,'text-anchor':'middle',class:'sketch-bend-label'},`B${b.number}`))});
 }
 function updateBendPositions(){
  const status=el('bendDataStatus'),footer=el('bendDataFooterStatus'),rows=el('bendDataRows'),pdf=el('exportBendDataPdf'),cutLength=el('bendDataCutLength');rows.replaceChildren();cutLength.textContent='Noch nicht berechnet';
  if(!activeProfile||!segments.length){drawBendSketch(null);pdf.disabled=true;status.textContent='Zeichne zuerst ein Rohr mit mindestens einer Biegung.';footer.textContent='Biegedaten: noch nicht berechnet';return}
  const result=bendPositions();drawBendSketch(Array.isArray(result)?result:null);
  if(!result){pdf.disabled=true;cutLength.textContent='Maße fehlen';status.textContent='Bitte zuerst alle Maße eingeben, damit die Biegedaten berechnet werden können.';footer.textContent='Biegedaten: Maße erforderlich';return}
  if(result.error){pdf.disabled=true;cutLength.textContent='Nicht berechenbar';status.textContent=result.error;footer.textContent='Biegedaten: Berechnung nicht möglich';return}
  const cut=sawLengthWithChuck();if(cut&&!cut.error)cutLength.textContent=`${cut.length.toFixed(1)} mm${cut.chuckExtension>0?` · Einspannzugabe +${cut.chuckExtension.toFixed(1)} mm`:''}`;else cutLength.textContent='Nicht berechenbar';
  if(!result.length){pdf.disabled=true;status.textContent='Die aktuelle Rohrform enthält keine Biegungen.';footer.textContent='Biegedaten: keine Biegungen';return}
  const ordered=[...result].sort((a,b)=>a.number-b.number);for(const b of ordered){const row=document.createElement('tr');[ `Biegung ${b.number}`,`${b.position.toFixed(1)} mm`,`${(b.angle*180/Math.PI).toFixed(0)}°`,`${activeProfile.radius.toFixed(1)} mm`,`${b.rotation.toFixed(0)}°` ].forEach(value=>{const cell=document.createElement('td');cell.textContent=value;row.append(cell)});rows.append(row)}
  pdf.disabled=false;status.textContent=`${result.length} Biegung${result.length===1?'':'en'} · Futterstellung ab 0°; Uhrzeigersinn positiv.`;footer.textContent=`Biegedaten: ${result.length} Biegung${result.length===1?'':'en'}`
 }
 function updateSawLength(){const out=el('sawLengthResult'),hint=el('cutAllowanceResult');hint.textContent='';if(!activeProfile||!segments.length){out.textContent='Sägelänge: noch nicht berechnet';return}const result=sawLengthWithChuck();if(!result){out.textContent='Sägelänge: Maße vollständig eingeben';return}if(result.error){out.textContent=`Sägelänge: ${result.error}`;return}out.textContent=`Sägelänge: ${result.length.toFixed(1)} mm · ${result.bends} Biegungen (geschätzt)`;if(result.chuckExtension>0)hint.textContent=`Einspannzugabe +${result.chuckExtension.toFixed(1)} mm · Überstand nach dem Biegen abschneiden`}
 function showProfileDialog(newPipe=false){pendingPipeChange=newPipe;hover=null;el('dimensionFields').replaceChildren();if(dimensionMode)stopDimensioning(false);drawingPaused=true;refreshProfileOptions();el('profileDialog').showModal();render()}
 function beginSelectedPipe(){const selected=profiles.find(p=>p.id===el('profileSelect').value);if(!selected)return;if(pendingPipeChange&&segments.length&&!confirm('Die aktuelle Zeichnung wird verworfen. Neues Rohr beginnen?'))return;segments=[];points=[[0,0,0]];currentIsometryId=null;el('currentIsometryName').value=`Isometrie ${(projectManifest?.isometries.length||0)+1}`;previousDir=offsetPreviousDir=continuationDir=null;offsetStage=0;offsetDir=offsetSideDir=offsetAnchor=null;dimensionMode=false;dimensionInputs=[];activeProfile=selected;el('activeProfileLabel').textContent=profileName(selected);el('profileDialog').close();pendingPipeChange=false;drawingPaused=false;hover=null;el('toolMode').textContent='ZEICHNEN · 3D';recalc();updatePrompt();updateSawLength();render()}
 function updatePrompt(){const p=el('prompt'),m=el('modeText');if(dimensionMode){p.innerHTML='<b>Bemaßung</b> · Werte eingeben und mit Enter zum nächsten Feld.';m.textContent='Maße eingeben'}else if(drawingPaused&&!activeProfile){p.innerHTML='<b>Rohr auswählen</b> · Wähle zuerst den Datensatz für diese Zeichnung.';m.textContent='Rohrdatensatz wählen'}else if(drawingPaused){p.innerHTML='<b>Bemaßung abgeschlossen</b> · Zum Zeichnen auf „Weiterzeichnen“ klicken.';m.textContent='Bereit zum Weiterzeichnen'}else if(offsetStage===1){p.innerHTML='<b>Offset · Schritt 1 von 3</b> · Laufrichtung wählen, rechts klicken.';m.textContent='Offset · R'}else if(offsetStage===2){p.innerHTML='<b>Offset · Schritt 2/3</b> · Seitlichen Versatz wählen; Rechtsklick beendet 2D, weiterer Rechtsklick ergänzt V.';m.textContent='Offset · H / optional V'}else{p.innerHTML='<b>Zeichnen bereit</b> · Maus bewegen, Richtungsvorschau sehen, links klicken zum Setzen.';m.textContent='Normales Rohrstück'}el('progress').textContent=`Rohrstücke: ${segments.length}`}
 canvas.addEventListener('contextmenu',e=>{e.preventDefault();if(drawingPaused||dimensionMode)return;if(offsetStage===2)moveEnd(mouse,true);commit('offset')});canvas.addEventListener('pointermove',e=>{const r=canvas.getBoundingClientRect(),pos=[e.clientX-r.left,e.clientY-r.top];if(dragging){if(dragMode==='pan'){pan[0]+=pos[0]-lastDrag[0];pan[1]+=pos[1]-lastDrag[1]}else{yaw+=(pos[0]-lastDrag[0])*.009;pitch=Math.max(.12,Math.min(1.35,pitch+(pos[1]-lastDrag[1])*.008))}lastDrag=pos;render();return}if(!dimensionMode&&!drawingPaused)moveEnd(pos)});canvas.addEventListener('pointerdown',e=>{if(e.button===1){e.preventDefault();dragging=true;dragMode=e.shiftKey?'pan':'rotate';lastDrag=[e.offsetX,e.offsetY];canvas.setPointerCapture(e.pointerId)}});canvas.addEventListener('pointerup',e=>{if(e.button===1)dragging=false});canvas.addEventListener('wheel',e=>{e.preventDefault();zoom=Math.max(.35,Math.min(3,zoom*Math.exp(-e.deltaY*.001)));render()},{passive:false});canvas.addEventListener('pointerleave',()=>{if(!dragging&&!dimensionMode){if(!drawingPaused)hover=null;render()}});canvas.addEventListener('click',e=>{if(e.button===0)commit('pipe')});
 el('openBendData').onclick=()=>{updateBendPositions();el('bendDataDialog').showModal()};el('closeBendData').onclick=()=>el('bendDataDialog').close();el('exportBendDataPdf').onclick=()=>{const oldTitle=document.title;document.title='RohrPlan - Biegedaten';document.body.classList.add('print-bend-data');window.addEventListener('afterprint',()=>{document.body.classList.remove('print-bend-data');document.title=oldTitle},{once:true});window.print()};el('dimension').onclick=()=>dimensionMode?stopDimensioning(true):drawingPaused?resumeDrawing():startDimensioning();el('undo').onclick=()=>{if(dimensionMode)stopDimensioning(true);if(offsetStage){offsetStage=0;offsetDir=offsetSideDir=offsetAnchor=offsetPreviousDir=null}else if(segments.length){segments.pop();previousDir=segments.length?dirs.find(d=>near(d.v,segments.at(-1).dir||segments.at(-1).sideDir?.v)):null}continuationDir=null;recalc();updatePrompt();updateSawLength();render()};el('clear').onclick=()=>{segments=[];points=[[0,0,0]];previousDir=offsetPreviousDir=continuationDir=null;offsetStage=0;offsetDir=offsetSideDir=offsetAnchor=null;if(dimensionMode)stopDimensioning(false);drawingPaused=!activeProfile;el('dimension').textContent='Bemaßen';target=[0,0,0];scale=34;updatePrompt();updateSawLength();updateBendPositions();render()};
 el('profileSelect').addEventListener('change',()=>{el('startPipe').disabled=!el('profileSelect').value});el('profileList').addEventListener('click',e=>{const button=e.target.closest('.delete-profile');if(button)deleteProfile(button.dataset.profileId)});el('openManager').onclick=()=>{el('profileDialog').close();renderProfileList();el('manageDialog').showModal()};el('closeManager').onclick=()=>{el('manageDialog').close();refreshProfileOptions();el('profileDialog').showModal()};el('addProfile').onclick=()=>{el('manageDialog').close();el('recordForm').reset();updateCalibrationPreview();el('recordDialog').showModal()};el('cancelRecord').onclick=()=>{el('recordDialog').close();renderProfileList();el('manageDialog').showModal()};el('cancelProfile').onclick=()=>el('profileDialog').close();el('startPipe').onclick=beginSelectedPipe;el('newPipe').onclick=()=>showProfileDialog(true);['recordDiameter','recordRadius','recordStartLength','recordLeg1','recordLeg2','recordLeg3'].forEach(id=>el(id).addEventListener('input',updateCalibrationPreview));
 el('recordForm').addEventListener('submit',e=>{e.preventDefault();const v={diameter:Number(el('recordDiameter').value),wall:Number(el('recordWall').value),radius:Number(el('recordRadius').value),sampleLength:Number(el('recordStartLength').value),legs:[Number(el('recordLeg1').value),Number(el('recordLeg2').value),Number(el('recordLeg3').value)]};if(![v.diameter,v.wall,v.radius,v.sampleLength,...v.legs].every(Number.isFinite)||!v.legs.every(x=>x>0)||![v.diameter,v.wall,v.radius,v.sampleLength].every(x=>x>0)){alert('Bitte alle Werte größer als 0 eingeben.');return}if(profiles.some(p=>p.diameter===v.diameter&&p.wall===v.wall&&p.radius===v.radius)){alert('Für diesen Durchmesser, diese Wandstärke und diesen Biegeradius gibt es bereits einen Datensatz.');return}const cal=calibration(v),record={id:globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`,...v,theoreticalSampleLength:cal.theoretical,correctionPer90:cal.per90,bendCount:2,bendAngle:90,createdAt:new Date().toISOString()};if(!persistProfiles([...profiles,record]))return;refreshProfileOptions();renderProfileList();el('recordDialog').close();el('manageDialog').showModal()});
 el('openProjects').onclick=openProjectsDialog;el('closeProjectDialog').onclick=()=>el('projectDialog').close();el('createProjectFolder').onclick=createProjectFolder;el('openProjectFolder').onclick=openProjectFolder;el('projectFileInput').addEventListener('change',e=>{const file=e.target.files?.[0];if(file)loadDownloadedProject(file)});el('saveCurrentToProject').onclick=saveCurrentIsometry;el('saveIsometry').onclick=()=>projectDirectoryHandle||projectFileMode?saveCurrentIsometry():(el('projectCurrentStatus').textContent='Lege zuerst ein Projekt an oder öffne eine Projektdatei.',el('projectDialog').showModal());el('projectIsometryList').addEventListener('click',e=>{const button=e.target.closest('[data-project-action]');if(!button)return;const id=button.dataset.id;if(button.dataset.projectAction==='load')loadProjectIsometry(id);if(button.dataset.projectAction==='delete')deleteProjectIsometry(id)});el('clear').addEventListener('click',()=>{currentIsometryId=null;updateProjectControls()});
 loadProfiles();refreshProfileOptions();renderProfileList();resize();updatePrompt();updateBendPositions();updateProjectControls();restoreRememberedProject();el('profileDialog').showModal();window.addEventListener('resize',resize);window.addEventListener('keydown',e=>{if(e.key==='Escape'){if(dimensionMode)stopDimensioning(true);else if(offsetStage){offsetStage=0;offsetDir=offsetSideDir=offsetAnchor=offsetPreviousDir=null;updatePrompt();render()}}});
})();
